name: XG_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas 
  - python[version'>=3.10']
  - cudatoolkit=11.8
  - tensorflow=2.12
  - scipy
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - sqlalchemy
  - xgboost
  - jupyter
  - nb_conda_kernels