name: XG_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas 
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip
  - pip:
    - tensorflow==2.10
  - scipy
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - sqlalchemy
  - psycopg2
  - xgboost
  - jupyter
  - nb_conda_kernels
# variables:
#   LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"