name: XG_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas 
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1
  - tensorflow=2.10
  - scipy
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - sqlalchemy
  - xgboost
  - jupyter
  - nb_conda_kernels